### ISSUE TITLE
Información faltante

### ISSUE THREAD

**Issue by restrepo** [colav/guatquyca#517]
En el nombre de los perfiles de Instituto se debería poner a que Facultad y Universidad está adscrito

http://impactu.colav.co/app/affiliation?type=department&id=63935abf71459ce0bcb933af&section=affiliations

Cambiar el título de 
```
Instituto de Física
```
a
```
Instituto de Física
Facultad de Ciencias Exactas y Naturales 
Universidad de Antioquia
```

En el nombre de los perfiles de Facultad se debería poner a que Universidad está adscrita

**Comment by luismvargasg** [comment]
La información de las afiliaciones fue añadida también a los resultados de búsqueda, anteriormente estaba solo en los perfiles individuales de cada entidad.
![image](https://github.com/colav/guatquyca/assets/60363752/17b44f67-7805-468f-8aec-d62976ab24e1)
